apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: sgmsmq7f8-python 
  janus-idp.io/tekton: sgmsmq7f8-python
  backstage.io/kubernetes-id: sgmsmq7f8-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: sgmsmq7f8-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  