apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: sgmsmq7f8-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sgmsmq7f8-python 
  name: sgmsmq7f8-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: sgmsmq7f8-python 
